<?php

/**
 * CssCode.php
 *
 * The CSS codes generated by a Jaxon plugin.
 *
 * @package jaxon-core
 * @author Thierry Feuzeu <thierry.feuzeu@gmail.com>
 * @copyright 2025 Thierry Feuzeu <thierry.feuzeu@gmail.com>
 * @license https://opensource.org/licenses/BSD-3-Clause BSD 3-Clause License
 * @link https://github.com/jaxon-php/jaxon-core
 */

namespace Jaxon\Plugin;

class CssCode
{
    /**
     * @param string $sCode
     * @param array $aFiles
     */
    public function __construct(protected string $sCode = '', protected array $aFiles = [])
    {}

    /**
     * Get the CSS code to include into the page
     *
     * The code must NOT be enclosed in HTML tags.
     *
     * @return string
     */
    public function code(): string
    {
        return $this->sCode;
    }

    /**
     * Get the CSS files to include into the page
     *
     * Each entry can be a string or an array with "uri" and "options".
     *
     * @return array
     */
    public function files(): array
    {
        return $this->aFiles;
    }
}
