<?php

/**
 * JsCode.php
 *
 * The javascript codes generated by a Jaxon plugin.
 *
 * @package jaxon-core
 * @author Thierry Feuzeu <thierry.feuzeu@gmail.com>
 * @copyright 2025 Thierry Feuzeu <thierry.feuzeu@gmail.com>
 * @license https://opensource.org/licenses/BSD-3-Clause BSD 3-Clause License
 * @link https://github.com/jaxon-php/jaxon-core
 */

namespace Jaxon\Plugin;

class JsCode
{
    /**
     * @param string $sCode
     * @param string $sHtml
     * @param array $aUrls
     * @param string $sCodeBefore
     * @param string $sCodeAfter
     */
    public function __construct(protected string $sCode = '',
        protected string $sHtml = '', protected array $aUrls = [],
        protected string $sCodeBefore = '', protected string $sCodeAfter = '')
    {}

    /**
     * Get the javascript files to include into the page
     *
     * Each entry can be a string or an array with "uri" and "options".
     *
     * @return array
     */
    public function urls(): array
    {
        return $this->aUrls;
    }

    /**
     * Get the javascript code to include into the page
     *
     * The code must NOT be enclosed in HTML tags.
     *
     * @return string
     */
    public function code(): string
    {
        return $this->sCode;
    }

    /**
     * Get the javascript code to include into the page
     *
     * The code must be enclosed in HTML tags.
     *
     * @return string
     */
    public function html(): string
    {
        return $this->sHtml;
    }

    /**
     * Get the javascript code to be inserted inline before the main code
     *
     * The code must NOT be enclosed in HTML tags.
     *
     * @return string
     */
    public function before(): string
    {
        return $this->sCodeBefore;
    }

    /**
     * Get the javascript code to be inserted inline after the main code
     *
     * The code must NOT be enclosed in HTML tags.
     *
     * @return string
     */
    public function after(): string
    {
        return $this->sCodeAfter;
    }
}
