<?php

/**
 * CodeGenerator.php
 *
 * Generate HTML, CSS and Javascript code for Jaxon.
 *
 * @package jaxon-core
 * @author Thierry Feuzeu <thierry.feuzeu@gmail.com>
 * @copyright 2016 Thierry Feuzeu <thierry.feuzeu@gmail.com>
 * @license https://opensource.org/licenses/BSD-3-Clause BSD 3-Clause License
 * @link https://github.com/jaxon-php/jaxon-core
 */

namespace Jaxon\Plugin\Code;

use Jaxon\App\Config\ConfigManager;
use Jaxon\Di\Container;
use Jaxon\Utils\Http\UriException;
use Jaxon\Utils\Template\TemplateEngine;

use function array_map;
use function count;
use function implode;
use function md5;
use function usort;

class CodeGenerator
{
    /**
     * @var StorageManager|null
     */
    private $xStorageManager = null;

    /**
     * @var array<string>
     */
    protected $aCodeGenerators = [];

    /**
     * @var Code|null
     */
    protected $xCode = null;

    /**
     * @var string
     */
    private const SEPARATOR = "\n\n";

    /**
     * @var int
     */
    private const TYPE_CSS_CODE = 1;

    /**
     * @var int
     */
    private const TYPE_JS_CODE = 2;

    /**
     * @var int
     */
    private const TYPE_CODE = 3;

    /**
     * The constructor
     *
     * @param string $sVersion
     * @param Container $di
     * @param TemplateEngine $xTemplateEngine
     * @param ConfigManager $xConfigManager
     */
    public function __construct(private string $sVersion, private Container $di,
        private TemplateEngine $xTemplateEngine, private ConfigManager $xConfigManager)
    {
        // The Jaxon library config is on top.
        $this->addJsCodeGenerator(ConfigScriptGenerator::class, 0);
        // The ready script comes after.
        $this->addJsCodeGenerator(ReadyScriptGenerator::class, 2);
    }

    /**
     * @return StorageManager
     */
    private function storage(): StorageManager
    {
        // Cannot be injected because of dependency loop.
        return $this->xStorageManager ??= $this->di->getStorageManager();
    }

    /**
     * Add a code generator to the list
     *
     * @param string $sClassName    The code generator class
     * @param int $nPriority    The desired priority, used to order the plugins
     *
     * @return void
     */
    public function addCssCodeGenerator(string $sClassName, int $nPriority): void
    {
        $this->aCodeGenerators[] = [$sClassName, self::TYPE_CSS_CODE, $nPriority];
    }

    /**
     * Add a code generator to the list
     *
     * @param string $sClassName    The code generator class
     * @param int $nPriority    The desired priority, used to order the plugins
     *
     * @return void
     */
    public function addJsCodeGenerator(string $sClassName, int $nPriority): void
    {
        $this->aCodeGenerators[] = [$sClassName, self::TYPE_JS_CODE, $nPriority];
    }

    /**
     * Add a code generator to the list
     *
     * @param string $sClassName    The code generator class
     * @param int $nPriority    The desired priority, used to order the plugins
     *
     * @return void
     */
    public function addCodeGenerator(string $sClassName, int $nPriority): void
    {
        $this->aCodeGenerators[] = [$sClassName, self::TYPE_CODE, $nPriority];
    }

    /**
     * Generate a hash for all the javascript code generated by the library
     *
     * @return string
     */
    public function getHash(): string
    {
        $aHashes = array_map(fn(array $aGenerator) =>
            $this->di->g($aGenerator[0])->getHash(), $this->aCodeGenerators);
        $aHashes[] = $this->sVersion;
        return md5(implode('', $aHashes));
    }

    /**
     * Render a template in the 'plugins' subdir
     *
     * @param string $sTemplate    The template filename
     * @param array $aVars    The template variables
     *
     * @return string
     */
    private function renderTemplate(string $sTemplate, array $aVars = []): string
    {
        return $this->xTemplateEngine->render("jaxon::plugins/$sTemplate", $aVars);
    }

    /**
     * @param array $aCssFile
     *
     * @return string
     */
    private function renderCssTag(array $aCssFile): string
    {
        return $this->renderTemplate('include.css', [
            'sUrl' => $aCssFile['uri'],
            'sOptions' => $this->storage()->makeFileOptions($aCssFile),
        ]);
    }

    /**
     * @param array $aJsFile
     *
     * @return string
     */
    private function renderJsTag(array $aJsFile): string
    {
        return $this->renderTemplate('include.js', [
            'sUrl' => $aJsFile['uri'],
            'sOptions' => $this->storage()->makeFileOptions($aJsFile),
        ]);
    }

    /**
     * Render a template in the 'plugins' subdir
     *
     * @param string $sTemplate    The template filename
     * @param array $aVars    The template variables
     *
     * @return string
     */
    private function render(string $sTemplate, array $aVars = []): string
    {
        $aVars['sJsOptions'] = $this->storage()->getJsOptions();
        return $this->xTemplateEngine->render("jaxon::plugins/$sTemplate", $aVars);
    }

    /**
     * Generate the Jaxon CSS ans js codes
     *
     * @return void
     * @throws UriException
     */
    private function generateCodes(): void
    {
        if($this->xCode !== null)
        {
            return;
        }

        $this->xCode = new Code();
        // We need the library to have been bootstrapped.
        $this->di->getBootstrap()->onBoot();

        // Sort the code generators by ascending priority
        usort($this->aCodeGenerators, fn(array $aGen1, array $aGen2) => $aGen1[2] - $aGen2[2]);

        // Load the Jaxon lib js files, before the other libs js files.
        $this->xCode->addJsTag(trim($this->renderTemplate('includes.js', [
            'aUrls' => $this->storage()->getJsLibFiles(),
            'sOptions' => $this->storage()->getJsOptions(),
        ])));

        $renderJsTag = fn(array $aJsFile) => $this->renderJsTag($aJsFile);
        $renderCssTag = fn(array $aCssFile) => $this->renderCssTag($aCssFile);
        foreach($this->aCodeGenerators as [$sClassName, $nType])
        {
            $xGenerator = $this->di->g($sClassName);
            $bIncludeAssets = $this->storage()->shallIncludeAssets($xGenerator);

            switch($nType)
            {
            case self::TYPE_CSS_CODE:
                $this->xCode->mergeCssCode($xGenerator, $renderCssTag, $bIncludeAssets);
                break;
            case self::TYPE_JS_CODE:
                $this->xCode->mergeJsCode($xGenerator, $renderJsTag, $bIncludeAssets);
                break;
            case self::TYPE_CODE:
                $this->xCode->mergeCode($xGenerator, $bIncludeAssets);
            }
        }
    }

    /**
     * Get the HTML tags to include Jaxon CSS code and files into the page
     *
     * @return string
     * @throws UriException
     */
    public function getCss(): string
    {
        $this->generateCodes();

        $aTags = $this->xCode->cssTags();
        $aCodes = $this->xCode->cssCodes();
        if(count($aCodes) === 0)
        {
            return implode(self::SEPARATOR, $aTags);
        }

        $cGetHash = fn() => $this->getHash();
        $cGetCode = fn() => implode(self::SEPARATOR, $aCodes);
        $sUrl = $this->storage()->createCssFiles($cGetHash, $cGetCode);
        // Wrap the js code into the corresponding HTML tag.
        $aTags[] = $sUrl !== '' ?
            // The generated code is saved to a file. Render the corresponding URL.
            $this->renderTemplate('include.css', [
                'sUrl' => $sUrl,
                'sOptions' => $this->storage()->getCssOptions(),
            ]) :
            // Otherwise, render the code.
            $this->renderTemplate('wrapper.css', [
                'sCode' => $cGetCode(),
                'sOptions' => $this->storage()->getCssOptions(),
            ]);

        return implode(self::SEPARATOR, $aTags);
    }

    /**
     * Get the HTML tags to include Jaxon javascript files into the page
     *
     * @return string
     * @throws UriException
     */
    public function getJs(): string
    {
        $this->generateCodes();

        return implode(self::SEPARATOR, $this->xCode->jsTags());
    }

    /**
     * Get the javascript code to be sent to the browser
     *
     * @param bool $bIncludeJs Also get the JS files
     * @param bool $bIncludeCss Also get the CSS files
     *
     * @return string
     * @throws UriException
     */
    public function getScript(bool $bIncludeJs, bool $bIncludeCss): string
    {
        $this->generateCodes();

        $aTags = [];
        if($bIncludeCss)
        {
            $aTags[] = $this->getCss();
        }
        if($bIncludeJs)
        {
            $aTags[] = $this->getJs();
        }

        $aJsOptions = $this->storage()->getJsOptions();

        $aJsCodes = $this->xCode->jsCodes();
        if(count($this->xCode->jsCodes()) > 0)
        {
            $cGetHash = fn() => $this->getHash();
            $cGetCode = fn() => implode(self::SEPARATOR, $aJsCodes);
            $sUrl = $this->storage()->createJsFiles($cGetHash, $cGetCode);
            // Wrap the js code into the corresponding HTML tag.
            $aTags[] = $sUrl !== '' ?
                // The generated code is saved to a file. Render the corresponding URL.
                $this->render('include.js', [
                    'sUrl' => $sUrl,
                    'sOptions' => $aJsOptions,
                ]) :
                // Otherwise, render the code.
                $this->render('wrapper.js', [
                    'sCode' => $cGetCode(),
                    'sOptions' => $aJsOptions,
                ]);
        }

        return implode(self::SEPARATOR, $aTags);
    }
}
