<?php

/**
 * Code.php
 *
 * Javascript and CSS codes generated by a Jaxon plugin.
 *
 * @package jaxon-core
 * @author Thierry Feuzeu <thierry.feuzeu@gmail.com>
 * @copyright 2025 Thierry Feuzeu <thierry.feuzeu@gmail.com>
 * @license https://opensource.org/licenses/BSD-3-Clause BSD 3-Clause License
 * @link https://github.com/jaxon-php/jaxon-core
 */

namespace Jaxon\Plugin\Code;

use Jaxon\Plugin\CodeGeneratorInterface;
use Jaxon\Plugin\CssCodeGeneratorInterface;
use Jaxon\Plugin\JsCodeGeneratorInterface;
use Closure;

use function is_array;
use function is_string;

class Code
{
    /**
     * @var array
     */
    protected $aCssTags = [];

    /**
     * @var array
     */
    protected $aCssCodes = [];

    /**
     * @var array
     */
    protected $aJsTags = [];

    /**
     * @var array
     */
    protected $aJsCodes = [];

    /**
     * @var array
     */
    protected $aJsCodesBefore = [];

    /**
     * @var array
     */
    protected $aJsCodesAfter = [];

    /**
     * @var string
     */
    protected CONST TRIM = " \t\r\n";

    /**
     * @return array
     */
    public function cssTags(): array
    {
        return $this->aCssTags;
    }

    /**
     * @param string $sTag
     *
     * @return void
     */
    public function addCssTag(string $sTag): void
    {
        $this->aCssTags[] = $sTag;
    }

    /**
     * @return array
     */
    public function cssCodes(): array
    {
        return $this->aCssCodes;
    }

    /**
     * @return array
     */
    public function jsTags(): array
    {
        return $this->aJsTags;
    }

    /**
     * @param string $sTag
     *
     * @return void
     */
    public function addJsTag(string $sTag): void
    {
        $this->aJsTags[] = $sTag;
    }

    /**
     * @return array
     */
    public function jsCodes(): array
    {
        return [
            ...$this->aJsCodesBefore,
            ...$this->aJsCodes,
            ...$this->aJsCodesAfter,
        ];
    }

    /**
     * @param CodeGeneratorInterface $xCodeGenerator
     *
     * @return void
     */
    public function mergeCode(CodeGeneratorInterface $xGenerator, bool $bIncludeAssets): void
    {
        if($bIncludeAssets)
        {
            // HTML tags for CSS
            if(($sCssTags = trim($xGenerator->getCss(), self::TRIM)) !== '')
            {
                $this->aCssTags[] = $sCssTags;
            }
            // HTML tags for js
            if(($sJsTags = trim($xGenerator->getJs(), self::TRIM)) !== '')
            {
                $this->aJsTags[] = $sJsTags;
            }
        }
        // Javascript code
        if(($sJsScript = trim($xGenerator->getScript(), self::TRIM)) !== '')
        {
            $this->aJsCodes[] = $sJsScript;
        }
    }

    /**
     * @param CodeGeneratorInterface $xCodeGenerator
     * @param Closure $renderTag
     *
     * @return void
     */
    public function mergeCssCode(CssCodeGeneratorInterface $xGenerator,
        Closure $renderTag, bool $bIncludeAssets): void
    {
        $xCode = $xGenerator->getCssCode();
        if($bIncludeAssets)
        {
            // CSS html tags
            if(($aCssHtml = trim($xCode->html(), self::TRIM)) !== '')
            {
                $this->aCssTags[] = $aCssHtml;
            }
            // HTML tags for CSS
            foreach($xCode->urls() as $xUrl)
            {
                $aCssFile = match(true) {
                    is_string($xUrl) => ['uri' => $xUrl, 'options' => []],
                    is_array($xUrl) => $xUrl,
                    default => null,
                };
                if($aCssFile !== null)
                {
                    // Save the HTML tag for the file.
                    $this->aCssTags[] = $renderTag($aCssFile);
                }
            }
        }
        // CSS code
        if(($aCssCode = trim($xCode->code(), self::TRIM)) !== '')
        {
            $this->aCssCodes[] = $aCssCode;
        }
    }

    /**
     * @param CodeGeneratorInterface $xCodeGenerator
     * @param Closure $renderTag
     *
     * @return void
     */
    public function mergeJsCode(JsCodeGeneratorInterface $xGenerator,
        Closure $renderTag, bool $bIncludeAssets): void
    {
        $xCode = $xGenerator->getJsCode();
        if($bIncludeAssets)
        {
            // Javascript html tags
            if(($aJsHtml = trim($xCode->html(), self::TRIM)) !== '')
            {
                $this->aJsTags[] = $aJsHtml;
            }
            // HTML tags for js
            foreach($xCode->urls() as $xUrl)
            {
                $aJsFile = match(true) {
                    is_string($xUrl) => ['uri' => $xUrl, 'options' => []],
                    is_array($xUrl) => $xUrl,
                    default => null,
                };
                if($aJsFile !== null)
                {
                    // Save the HTML tag for the file.
                    $this->aJsTags[] = $renderTag($aJsFile);
                }
            }
        }
        // Javascript codes
        if(($aJsCode = trim($xCode->code(), self::TRIM)) !== '')
        {
            $this->aJsCodes[] = $aJsCode;
        }
        // Javascript codes before the main code
        if(($aJsCode = trim($xCode->before(), self::TRIM)) !== '')
        {
            $this->aJsCodesBefore[] = $aJsCode;
        }
        // Javascript codes after the main code
        if(($aJsCode = trim($xCode->after(), self::TRIM)) !== '')
        {
            $this->aJsCodesAfter[] = $aJsCode;
        }
    }
}
